# This is a basic workflow to help you get started with Actions

name: Chrome UI Tests

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  chrome-ui-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (API)
        working-directory: samuraibs/api
        run: yarn install

      - name: Install Dependencies (Web)
        working-directory: samuraibs/web
        run: yarn install

      - name: Initialize API
        working-directory: samuraibs/api
        run: yarn start &

      - name: Initialize Web
        working-directory: samuraibs/api
        run: yarn start &

      - name: Install Dependencies (Tests)
        working-directory: samuraibs/tests
        run: yarn install

      - name: Run Cypress Tests
        working-directory: samuraibs/tests
        run: npx cypress run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
