name: Run Cypress Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: samuraibs/tests
        run: yarn install

      - name: Build API
        working-directory: samuraibs/api
        run: yarn build

      - name: Start API Server
        working-directory: samuraibs/api
        run: |
          yarn start &
          sleep 10 # Ajuste o tempo conforme necessário

      - name: Start Web Server
        working-directory: samuraibs/web
        run: |
          yarn start &
          sleep 10 # Ajuste o tempo conforme necessário

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
