# This is a basic workflow to help you get started with Actions

name: Chrome UI Tests

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  chrome-ui-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (API)
        working-directory: samuraibs/api
        run: yarn install && yarn start &

      - name: Install Dependencies (Web)
        working-directory: samuraibs/web
        run: yarn install && yarn start &

      - name: Install Dependencies (Tests)
        working-directory: samuraibs/tests
        run: yarn install

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          wait-on: 'http://localhost:3000' # Waiting for the web server to be available
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/integration/*
        env:
          TZ: America/Sao_Paulo
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
